kind: pipeline
type: docker
name: RailsOverflow 
steps:
- name: Run linter
  image: ruby:3.1.2
  environment:
    BUNDLE_PATH: /drone-pipeline/${DRONE_REPO}/bundle/vendor
    BUNDLE_CACHE_PATH: /drone-pipeline/${DRONE_REPO}/bundle/cache
    DATABASE_NAME: rails_overflow_test
    DB_HOST: postgres-service
    DB_PORT: 5432
    DB_USERNAME: test_user
    DB_PASSWORD: password123
  commands:
    - bundle package
    - bundle exec rubocop
    - bundle exec rspec
services:
  - name: postgres-service
    image: postgres:14
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password123