kind: pipeline
type: docker
name: RailsOverflow 
steps:
- name: Run linter
  image: ruby:3.1.2
  environment:
    BUNDLE_PATH: /drone-pipeline/${DRONE_REPO}/bundle/vendor
    BUNDLE_CACHE_PATH: /drone-pipeline/${DRONE_REPO}/bundle/cache
  commands:
    - bundle package
    - bundle exec rubocop
    - bundle exec rspec spec/models