AllCops:
  Excludes:
    - db/**
    - config/**
    - script/**
    - vendor/**/*
    - bin/**

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 1000

Metrics/MethodLength:
  Max: 150
